ServerEvents.recipes((event) => {
  let recipes = [
    {
      ingredient: { item: "kubejs:raw_tin_bloom" },
      result: { id: "tfc:metal/ingot/tin" },
      tier: 1,
      rules: ["hit_last", "hit_second_last", "hit_third_last"],
      id: "may:anvil/tin_from_bloom",
    },
    {
      ingredient: { item: "kubejs:raw_copper_bloom" },
      result: { id: "tfc:metal/ingot/copper" },
      tier: 1,
      rules: ["hit_last", "hit_second_last", "hit_third_last"],
      id: "may:anvil/copper_from_bloom",
    },
    {
      ingredient: { item: "tfc:metal/sheet/copper" },
      result: { id: "create:copper_backtank" },
      tier: 1,
      rules: ["hit_last", "hit_second_last", "hit_third_last"],
      id: "may:anvil/copper_backtank",
    },
    {
      ingredient: { item: "tfc:metal/sheet/wrought_iron" },
      result: { id: "create:chute" },
      tier: 3,
      rules: ["hit_last", "hit_second_last", "hit_third_last"],
      id: "may:anvil/chute",
    },
    {
      ingredient: { item: "tfc:metal/double_sheet/wrought_iron" },
      result: { id: "minecraft:cauldron" },
      tier: 3,
      rules: ["hit_last", "hit_second_last", "hit_third_last"],
      id: "may:anvil/cauldron",
    },
    {
      ingredient: { item: "tfc:metal/double_sheet/wrought_iron" },
      result: { id: "create:basin" },
      tier: 3,
      rules: ["hit_last", "hit_second_last", "hit_third_last"],
      id: "may:anvil/basin",
    },
    {
      ingredient: { item: "tfc:metal/rod/wrought_iron" },
      result: { id: "kubejs:metal/spindle_head/wrought_iron" },
      tier: 3,
      rules: ["hit_last", "hit_second_last", "hit_third_last"],
      id: "may:anvil/spindle_head/wrought_iron",
    },
    {
      ingredient: { item: "tfc:metal/rod/bronze" },
      result: { id: "kubejs:metal/spindle_head/bronze" },
      tier: 2,
      rules: ["hit_last", "hit_second_last", "hit_third_last"],
      id: "may:anvil/spindle_head/bronze",
    },
    {
      ingredient: { item: "tfc:metal/rod/copper" },
      result: { id: "kubejs:metal/spindle_head/copper" },
      tier: 1,
      rules: ["hit_last", "hit_second_last", "hit_third_last"],
      id: "may:anvil/spindle_head/copper",
    },
    {
      type: "tfc:anvil",
      apply_bonus: true,
      ingredient: { tag: "c:ingots/osmirite" },
      result: { count: 1, id: "kubejs:metal/axe_head/osmirite" },
      rules: ["upset_third_last", "hit_second_last", "punch_last"],
      tier: 6,
      id: "may:anvil/metal/axe_head/osmirite",
    },
    {
      type: "tfc:anvil",
      apply_bonus: true,
      ingredient: { tag: "c:ingots/osmirite" },
      result: { count: 1, id: "kubejs:metal/chisel_head/osmirite" },
      rules: ["hit_not_last", "draw_not_last", "hit_last"],
      tier: 6,
      id: "may:anvil/metal/chisel_head/osmirite",
    },
    {
      type: "tfc:anvil",
      apply_bonus: true,
      ingredient: { tag: "c:sheets/osmirite" },
      result: { count: 1, id: "kubejs:metal/fish_hook/osmirite" },
      rules: ["draw_not_last", "bend_any", "hit_any"],
      tier: 6,
      id: "may:anvil/metal/fish_hook/osmirite",
    },
    {
      type: "tfc:anvil",
      apply_bonus: true,
      ingredient: { tag: "c:ingots/osmirite" },
      result: { count: 1, id: "kubejs:metal/hammer_head/osmirite" },
      rules: ["shrink_not_last", "punch_last"],
      tier: 6,
      id: "may:anvil/metal/hammer_head/osmirite",
    },
    {
      type: "tfc:anvil",
      apply_bonus: true,
      ingredient: { tag: "c:ingots/osmirite" },
      result: { count: 1, id: "kubejs:metal/hoe_head/osmirite" },
      rules: ["bend_not_last", "hit_not_last", "punch_last"],
      tier: 6,
      id: "may:anvil/metal/hoe_head/osmirite",
    },
    {
      type: "tfc:anvil",
      apply_bonus: true,
      ingredient: { tag: "c:ingots/osmirite" },
      result: { count: 1, id: "kubejs:metal/javelin_head/osmirite" },
      rules: ["draw_third_last", "hit_second_last", "hit_last"],
      tier: 6,
      id: "may:anvil/metal/javelin_head/osmirite",
    },
    {
      type: "tfc:anvil",
      apply_bonus: true,
      ingredient: { tag: "c:ingots/osmirite" },
      result: { count: 1, id: "kubejs:metal/knife_head/osmirite" },
      rules: ["draw_third_last", "draw_second_last", "hit_last"],
      tier: 6,
      id: "may:anvil/metal/knife_head/osmirite",
    },
    {
      type: "tfc:anvil",
      apply_bonus: true,
      ingredient: { tag: "c:double_ingots/osmirite" },
      result: { count: 1, id: "kubejs:metal/mace_head/osmirite" },
      rules: ["shrink_not_last", "bend_not_last", "hit_last"],
      tier: 6,
      id: "may:anvil/metal/mace_head/osmirite",
    },
    {
      type: "tfc:anvil",
      apply_bonus: true,
      ingredient: { tag: "c:ingots/osmirite" },
      result: { count: 1, id: "kubejs:metal/pickaxe_head/osmirite" },
      rules: ["bend_not_last", "draw_not_last", "punch_last"],
      tier: 6,
      id: "may:anvil/metal/pickaxe_head/osmirite",
    },
    {
      type: "tfc:anvil",
      apply_bonus: true,
      ingredient: { tag: "c:ingots/osmirite" },
      result: { count: 1, id: "kubejs:metal/propick_head/osmirite" },
      rules: ["draw_not_last", "bend_not_last", "punch_last"],
      tier: 6,
      id: "may:anvil/metal/propick_head/osmirite",
    },
    {
      type: "tfc:anvil",
      apply_bonus: true,
      ingredient: { tag: "c:ingots/osmirite" },
      result: { count: 1, id: "kubejs:metal/saw_head/osmirite" },
      rules: ["hit_second_last", "hit_last"],
      tier: 6,
      id: "may:anvil/metal/saw_head/osmirite",
    },
    {
      type: "tfc:anvil",
      apply_bonus: true,
      ingredient: { tag: "c:ingots/osmirite" },
      result: { count: 1, id: "kubejs:metal/scythe_head/osmirite" },
      rules: ["bend_third_last", "draw_second_last", "hit_last"],
      tier: 6,
      id: "may:anvil/metal/scythe_head/osmirite",
    },
    {
      type: "tfc:anvil",
      apply_bonus: true,
      ingredient: { tag: "c:ingots/osmirite" },
      result: { count: 1, id: "kubejs:metal/shovel_head/osmirite" },
      rules: ["hit_not_last", "punch_last"],
      tier: 6,
      id: "may:anvil/metal/shovel_head/osmirite",
    },
    {
      type: "tfc:anvil",
      apply_bonus: true,
      ingredient: { tag: "c:double_ingots/osmirite" },
      result: { count: 1, id: "kubejs:metal/sword_head/osmirite" },
      rules: ["bend_third_last", "bend_second_last", "hit_last"],
      tier: 6,
      id: "may:anvil/metal/sword_head/osmirite",
    },
    {
      type: "tfc:anvil",
      apply_bonus: true,
      ingredient: { tag: "c:double_ingots/osmirite" },
      result: { count: 1, id: "kubejs:metal/mineral_prospector_head/osmirite" },
      rules: ["hit_last", "draw_not_last"],
      tier: 6,
      id: "may:anvil/metal/mineral_prospector_head/osmirite",
    },
    {
      type: "tfc:anvil",
      apply_bonus: true,
      ingredient: { item: "kubejs:metal/tuyere/osmirite" },
      result: { count: 1, id: "kubejs:metal/prospector_drill_head/osmirite" },
      rules: ["punch_last", "hit_any", "hit_any"],
      tier: 6,
      id: "may:anvil/metal/prospector_drill_head/osmirite",
    },
    {
      type: "tfc:anvil",
      apply_bonus: true,
      ingredient: { tag: "c:double_ingots/osmirite" },
      result: { count: 1, id: "kubejs:metal/prospector_hammer_head/osmirite" },
      rules: ["punch_last", "shrink_not_last"],
      tier: 6,
      id: "may:anvil/metal/prospector_hammer_head/osmirite",
    },
    {
      type: "tfc:anvil",
      ingredient: { tag: "c:double_ingots/osmirite" },
      result: { count: 1, id: "kubejs:metal/sheet/osmirite" },
      rules: ["hit_third_last", "hit_second_last", "hit_last"],
      tier: 6,
      id: "may:anvil/metal/sheet/osmirite",
    },
    {
      type: "tfc:anvil",
      ingredient: { tag: "c:sheets/osmirite" },
      result: { count: 1, id: "kubejs:metal/tuyere/osmirite" },
      rules: ["bend_second_last", "bend_last"],
      tier: 6,
      id: "may:anvil/metal/tuyere/osmirite",
    },
  ];

  recipes.forEach((recipe) => {
    recipe.type = "tfc:anvil";
    event.custom(recipe).id(recipe.id);
  });
});
