//priority: 999
global.mineralVeinsList = [
  // {
  //   name: "chromite",
  //   ie: {
  //     weight: 25,
  //     failChance: 0.1,
  //     dimensions: ["minecraft:overworld"],
  //     ores: [{ ore: "firmalife:ore/small_chromite", chance: 0.75 }],
  //     spoils: [{ ore: "tfc:rock/raw/marble", chance: 0.5 }],
  //   },
  //   coe: {
  //     spacing:
  //     separation:
  //     salt:
  //     size: { min: 1, max: 2}
  //     ticks: 0,
  //     drill: "",
  //     stress: 0,
  //     fluid: {},
  //     outputs: [],
  //   },
  // },
  {
    name: "aikinite",
    ie: {
      weight: 20,
      failChance: 0.1,
      ores: [
        { ore: "tfc:ore/small_tetrahedrite", chance: 0.15 },
        { ore: "tfc:ore/poor_tetrahedrite", chance: 0.11 },
        { ore: "tfc:ore/normal_tetrahedrite", chance: 0.07 },
        { ore: "tfc:ore/rich_tetrahedrite", chance: 0.04 },
        { ore: "tfc:ore/small_cassiterite", chance: 0.15 },
        { ore: "tfc:ore/poor_cassiterite", chance: 0.11 },
        { ore: "tfc:ore/normal_cassiterite", chance: 0.07 },
        { ore: "tfc:ore/rich_cassiterite", chance: 0.04 },
        { ore: "tfc:ore/small_limonite", chance: 0.08 },
        { ore: "tfc:ore/poor_limonite", chance: 0.05 },
        { ore: "tfc:ore/normal_limonite", chance: 0.04 },
        { ore: "tfc:ore/rich_limonite", chance: 0.02 },
        { ore: "tfc:ore/sulfur", chance: 0.07 },
      ],
      spoils: [
        { spoil: "tfc:rock/raw/marble", chance: 0.35 },
        { spoil: "tfc:rock/gravel/marble", chance: 0.15 },
        { spoil: "tfc:rock/raw/andesite", chance: 0.35 },
        { spoil: "tfc:rock/gravel/andesite", chance: 0.15 },
      ],
    },
    coe: {
      spacing: 128,
      separation: 16,
      salt: 714636,
      size: { min: 2, max: 4 },
      outputs: [
        Item.of("tfc:ore/normal_tetrahedrite").withChance(0.2),
        Item.of("tfc:ore/rich_tetrahedrite").withChance(0.1),
        Item.of("tfc:ore/normal_cassiterite").withChance(0.2),
        Item.of("tfc:ore/rich_cassiterite").withChance(0.1),
        Item.of("tfc:ore/normal_limonite").withChance(0.1),
        Item.of("tfc:ore/rich_limonite").withChance(0.1),
        Item.of("tfc:ore/sulfur").withChance(0.1),
        Item.of("tfc:rock/loose/marble").withChance(0.05),
        Item.of("tfc:rock/loose/andesite").withChance(0.05),
      ],
    },
  },
  {
    name: "auricupride",
    ie: {
      weight: 30,
      failChance: 0.1,
      ores: [
        { ore: "tfc:ore/small_native_gold", chance: 0.11 },
        { ore: "tfc:ore/poor_native_gold", chance: 0.09 },
        { ore: "tfc:ore/normal_native_gold", chance: 0.07 },
        { ore: "tfc:ore/rich_native_gold", chance: 0.05 },
        { ore: "tfc:ore/small_native_copper", chance: 0.26 },
        { ore: "tfc:ore/poor_native_copper", chance: 0.21 },
        { ore: "tfc:ore/normal_native_copper", chance: 0.14 },
        { ore: "tfc:ore/rich_native_copper", chance: 0.07 },
      ],
      spoils: [
        { spoil: "tfc:rock/raw/diorite", chance: 0.35 },
        { spoil: "tfc:rock/gravel/diorite", chance: 0.15 },
        { spoil: "tfc:rock/raw/granite", chance: 0.35 },
        { spoil: "tfc:rock/gravel/granite", chance: 0.15 },
      ],
    },
    coe: {
      spacing: 128,
      separation: 16,
      salt: 1414646,
      size: { min: 2, max: 4 },
      outputs: [
        Item.of("tfc:ore/normal_native_copper").withChance(0.3),
        Item.of("tfc:ore/rich_native_copper").withChance(0.3),
        Item.of("tfc:ore/normal_native_gold").withChance(0.2),
        Item.of("tfc:ore/rich_native_gold").withChance(0.1),
        Item.of("tfc:rock/loose/diorite").withChance(0.05),
        Item.of("tfc:rock/loose/granite").withChance(0.05),
      ],
    },
  },
  {
    name: "bituminous_coal",
    ie: {
      weight: 25,
      failChance: 0.05,
      ores: [
        { ore: "tfc:ore/bituminous_coal", chance: 0.8 },
        { ore: "tfc:ore/sulfur", chance: 0.2 },
      ],
      spoils: [
        { spoil: "tfc:rock/raw/basalt", chance: 0.35 },
        { spoil: "tfc:rock/gravel/basalt", chance: 0.15 },
        { spoil: "tfc:rock/raw/chalk", chance: 0.35 },
        { spoil: "tfc:rock/gravel/chalk", chance: 0.15 },
      ],
    },
    coe: {
      spacing: 128,
      separation: 16,
      salt: 1736437,
      size: { min: 4, max: 6 },
      outputs: [
        Item.of("tfc:ore/bituminous_coal").withChance(0.75),
        Item.of("tfc:ore/sulfur").withChance(0.2),
        Item.of("tfc:rock/loose/basalt").withChance(0.025),
        Item.of("tfc:rock/loose/chalk").withChance(0.025),
      ],
    },
  },
  {
    name: "chalcopyrite",
    ie: {
      weight: 20,
      failChance: 0.05,
      ores: [
        { ore: "tfc:ore/small_native_copper", chance: 0.22 },
        { ore: "tfc:ore/poor_native_copper", chance: 0.18 },
        { ore: "tfc:ore/normal_native_copper", chance: 0.12 },
        { ore: "tfc:ore/rich_native_copper", chance: 0.06 },
        { ore: "tfc:ore/small_hematite", chance: 0.15 },
        { ore: "tfc:ore/poor_hematite", chance: 0.09 },
        { ore: "tfc:ore/normal_hematite", chance: 0.06 },
        { ore: "tfc:ore/rich_hematite", chance: 0.03 },
        { ore: "tfc:ore/sulfur", chance: 0.09 },
      ],
      spoils: [
        { spoil: "tfc:rock/raw/dacite", chance: 0.35 },
        { spoil: "tfc:rock/gravel/dacite", chance: 0.15 },
        { spoil: "tfc:rock/raw/slate", chance: 0.35 },
        { spoil: "tfc:rock/gravel/slate", chance: 0.15 },
      ],
    },
    coe: {
      spacing: 128,
      separation: 16,
      salt: 612050,
      size: { min: 2, max: 4 },
      outputs: [
        Item.of("tfc:ore/normal_native_copper").withChance(0.3),
        Item.of("tfc:ore/rich_native_copper").withChance(0.25),
        Item.of("tfc:ore/normal_hematite").withChance(0.2),
        Item.of("tfc:ore/rich_hematite").withChance(0.1),
        Item.of("tfc:ore/sulfur").withChance(0.1),
        Item.of("tfc:rock/loose/dacite").withChance(0.025),
        Item.of("tfc:rock/loose/slate").withChance(0.025),
      ],
    },
  },
  {
    name: "chromite",
    ie: {
      weight: 20,
      failChance: 0.1,
      ores: [
        { ore: "firmalife:ore/small_chromite", chance: 0.26 },
        { ore: "firmalife:ore/poor_chromite", chance: 0.21 },
        { ore: "firmalife:ore/normal_chromite", chance: 0.14 },
        { ore: "firmalife:ore/rich_chromite", chance: 0.07 },
        { ore: "tfc:ore/small_magnetite", chance: 0.11 },
        { ore: "tfc:ore/poor_magnetite", chance: 0.09 },
        { ore: "tfc:ore/normal_magnetite", chance: 0.07 },
        { ore: "tfc:ore/rich_magnetite", chance: 0.05 },
      ],
      spoils: [
        { spoil: "tfc:rock/raw/basalt", chance: 0.35 },
        { spoil: "tfc:rock/gravel/basalt", chance: 0.15 },
        { spoil: "tfc:rock/raw/gneiss", chance: 0.35 },
        { spoil: "tfc:rock/gravel/gneiss", chance: 0.15 },
      ],
    },
    coe: {
      spacing: 128,
      separation: 16,
      salt: 2452761,
      size: { min: 2, max: 4 },
      outputs: [
        Item.of("firmalife:ore/normal_chromite").withChance(0.3),
        Item.of("firmalife:ore/rich_chromite").withChance(0.3),
        Item.of("tfc:ore/normal_magnetite").withChance(0.2),
        Item.of("tfc:ore/rich_magnetite").withChance(0.1),
        Item.of("tfc:rock/loose/basalt").withChance(0.05),
        Item.of("tfc:rock/loose/gneiss").withChance(0.05),
      ],
    },
  },
  {
    name: "cinnabar",
    ie: {
      weight: 15,
      failChance: 0.1,
      ores: [
        { ore: "tfc:ore/cinnabar", chance: 0.6 },
        { ore: "tfc:ore/sulfur", chance: 0.4 },
      ],
      spoils: [
        { spoil: "tfc:rock/raw/gabbro", chance: 0.35 },
        { spoil: "tfc:rock/gravel/gabbro", chance: 0.15 },
        { spoil: "tfc:rock/raw/schist", chance: 0.35 },
        { spoil: "tfc:rock/gravel/schist", chance: 0.15 },
      ],
    },
    coe: {
      spacing: 128,
      separation: 16,
      salt: 2673328,
      size: { min: 1, max: 2 },
      outputs: [
        Item.of("tfc:ore/cinnabar").withChance(0.6),
        Item.of("tfc:ore/sulfur").withChance(0.3),
        Item.of("tfc:rock/loose/gabbro").withChance(0.05),
        Item.of("tfc:rock/loose/schist").withChance(0.05),
      ],
    },
  },
  {
    name: "erlichmanite",
    ie: {
      weight: 10,
      failCHance: 0.1,
      ores: [
        { ore: "kubejs:ore/small_erlichmanite", chance: 0.26 },
        { ore: "kubejs:ore/poor_erlichmanite", chance: 0.21 },
        { ore: "kubejs:ore/normal_erlichmanite", chance: 0.14 },
        { ore: "kubejs:ore/rich_erlichmanite", chance: 0.07 },
        { ore: "firmalife:ore/small_chromite", chance: 0.11 },
        { ore: "firmalife:ore/poor_chromite", chance: 0.09 },
        { ore: "firmalife:ore/normal_chromite", chance: 0.07 },
        { ore: "firmalife:ore/rich_chromite", chance: 0.05 },
      ],
      spoils: [
        { spoil: "tfc:rock/raw/chalk", chance: 0.35 },
        { spoil: "tfc:rock/gravel/chalk", chance: 0.15 },
        { spoil: "tfc:rock/raw/limestone", chance: 0.35 },
        { spoil: "tfc:rock/gravel/limestone", chance: 0.15 },
      ],
    },
    coe: {
      spacing: 256,
      separation: 32,
      salt: 1534597,
      size: { min: 1, max: 2 },
      outputs: [
        Item.of("kubejs:ore/normal_erlichmanite").withChance(0.3),
        Item.of("kubejs:ore/rich_erlichmanite").withChance(0.3),
        Item.of("firmalife:ore/normal_chromite").withChance(0.2),
        Item.of("firmalife:ore/rich_chromite").withChance(0.1),
        Item.of("tfc:rock/loose/chalk").withChance(0.05),
        Item.of("tfc:rock/loose/limestone").withChance(0.05),
      ],
    },
  },
  {
    name: "franklinite",
    ie: {
      weight: 25,
      failChance: 0.05,
      ores: [
        { ore: "tfc:ore/small_sphalerite", chance: 0.16 },
        { ore: "tfc:ore/poor_sphalerite", chance: 0.11 },
        { ore: "tfc:ore/normal_sphalerite", chance: 0.09 },
        { ore: "tfc:ore/rich_sphalerite", chance: 0.05 },
        { ore: "tfc:ore/small_hematite", chance: 0.27 },
        { ore: "tfc:ore/poor_hematite", chance: 0.18 },
        { ore: "tfc:ore/normal_hematite", chance: 0.09 },
        { ore: "tfc:ore/rich_hematite", chance: 0.05 },
      ],
      spoils: [
        { spoil: "tfc:rock/raw/shale", chance: 0.35 },
        { spoil: "tfc:rock/gravel/shale", chance: 0.15 },
        { spoil: "tfc:rock/raw/conglomerate", chance: 0.35 },
        { spoil: "tfc:rock/gravel/conglomerate", chance: 0.15 },
      ],
    },
    coe: {
      spacing: 128,
      separation: 16,
      salt: 939917,
      size: { min: 2, max: 4 },
      outputs: [
        Item.of("tfc:ore/normal_hematite").withChance(0.35),
        Item.of("tfc:ore/rich_hematite").withChance(0.3),
        Item.of("tfc:ore/normal_sphalerite").withChance(0.2),
        Item.of("tfc:ore/rich_sphalerite").withChance(0.1),
        Item.of("tfc:rock/loose/shale").withChance(0.025),
        Item.of("tfc:rock/loose/conglomerate").withChance(0.025),
      ],
    },
  },
  {
    name: "galena",
    ie: {
      weight: 15,
      failChance: 0.05,
      ores: [
        { ore: "tfc_ie_addon:ore/small_galena", chance: 0.19 },
        { ore: "tfc_ie_addon:ore/poor_galena", chance: 0.14 },
        { ore: "tfc_ie_addon:ore/normal_galena", chance: 0.1 },
        { ore: "tfc_ie_addon:ore/rich_galena", chance: 0.05 },
        { ore: "tfc:ore/small_native_silver", chance: 0.12 },
        { ore: "tfc:ore/poor_native_silver", chance: 0.1 },
        { ore: "tfc:ore/normal_native_silver", chance: 0.07 },
        { ore: "tfc:ore/rich_native_silver", chance: 0.05 },
        { ore: "tfc:ore/sulfur", chance: 0.18 },
      ],
      spoils: [
        { spoil: "tfc:rock/raw/limestone", chance: 0.35 },
        { spoil: "tfc:rock/gravel/limestone", chance: 0.15 },
        { spoil: "tfc:rock/raw/quartzite", chance: 0.35 },
        { spoil: "tfc:rock/gravel/quartzite", chance: 0.15 },
      ],
    },
    coe: {
      spacing: 128,
      separation: 16,
      salt: 2451942,
      size: { min: 1, max: 2 },
      outputs: [
        Item.of("tfc_ie_addon:ore/normal_galena").withChance(0.3),
        Item.of("tfc_ie_addon:ore/rich_galena").withChance(0.2),
        Item.of("tfc:ore/normal_native_silver").withChance(0.2),
        Item.of("tfc:ore/rich_native_silver").withChance(0.15),
        Item.of("tfc:ore/sulfur").withChance(0.1),
        Item.of("tfc:rock/loose/limestone").withChance(0.025),
        Item.of("tfc:rock/loose/quartzite").withChance(0.025),
      ],
    },
  },
  {
    name: "laterite",
    ie: {
      weight: 20,
      failChance: 0.05,
      ores: [
        { ore: "tfc_ie_addon:ore/small_bauxite", chance: 0.27 },
        { ore: "tfc_ie_addon:ore/poor_bauxite", chance: 0.19 },
        { ore: "tfc_ie_addon:ore/normal_bauxite", chance: 0.15 },
        { ore: "tfc_ie_addon:ore/rich_bauxite", chance: 0.08 },
        { ore: "tfc:ore/small_magnetite", chance: 0.11 },
        { ore: "tfc:ore/poor_magnetite", chance: 0.1 },
        { ore: "tfc:ore/normal_magnetite", chance: 0.06 },
        { ore: "tfc:ore/rich_magnetite", chance: 0.04 },
      ],
      spoils: [
        { spoil: "tfc:rock/raw/marble", chance: 0.35 },
        { spoil: "tfc:rock/gravel/marble", chance: 0.15 },
        { spoil: "tfc:rock/raw/phyllite", chance: 0.35 },
        { spoil: "tfc:rock/gravel/phyllite", chance: 0.15 },
      ],
    },
    coe: {
      spacing: 128,
      separation: 16,
      salt: 2928144,
      size: { min: 2, max: 4 },
      outputs: [
        Item.of("tfc_ie_addon:ore/normal_bauxite").withChance(0.35),
        Item.of("tfc_ie_addon:ore/rich_bauxite").withChance(0.25),
        Item.of("tfc:ore/normal_magnetite").withChance(0.25),
        Item.of("tfc:ore/rich_magnetite").withChance(0.1),
        Item.of("tfc:rock/loose/marble").withChance(0.025),
        Item.of("tfc:rock/loose/phyllite").withChance(0.025),
      ],
    },
  },
  {
    name: "pentlandite",
    ie: {
      weight: 25,
      failChance: 0.05,
      ores: [
        { ore: "tfc:ore/small_hematite", chance: 0.17 },
        { ore: "tfc:ore/poor_hematite", chance: 0.12 },
        { ore: "tfc:ore/normal_hematite", chance: 0.09 },
        { ore: "tfc:ore/rich_hematite", chance: 0.05 },
        { ore: "tfc:ore/small_garnierite", chance: 0.17 },
        { ore: "tfc:ore/poor_garnierite", chance: 0.12 },
        { ore: "tfc:ore/normal_garnierite", chance: 0.09 },
        { ore: "tfc:ore/rich_garnierite", chance: 0.05 },
        { ore: "tfc:ore/sulfur", chance: 0.14 },
      ],
      spoils: [
        { spoil: "tfc:rock/raw/chalk", chance: 0.35 },
        { spoil: "tfc:rock/gravel/chalk", chance: 0.15 },
        { spoil: "tfc:rock/raw/gneiss", chance: 0.35 },
        { spoil: "tfc:rock/gravel/gneiss", chance: 0.15 },
      ],
    },
    coe: {
      spacing: 128,
      separation: 16,
      salt: 1541942,
      size: { min: 2, max: 4 },
      outputs: [
        Item.of("tfc:ore/normal_hematite").withChance(0.3),
        Item.of("tfc:ore/rich_hematite").withChance(0.25),
        Item.of("tfc:ore/normal_garnierite").withChance(0.2),
        Item.of("tfc:ore/rich_garnierite").withChance(0.1),
        Item.of("tfc:ore/sulfur").withChance(0.1),
        Item.of("tfc:rock/loose/chalk").withChance(0.025),
        Item.of("tfc:rock/loose/gneiss").withChance(0.025),
      ],
    },
  },
  {
    name: "quartzite",
    ie: {
      weight: 20,
      failChance: 0.15,
      ores: [
        { ore: "tfc_ie_addon:mineral/quartz_block", chance: 0.5 },
        { ore: "tfc_ie_addon:mineral/quartz_shard", chance: 0.3 },
        { ore: "tfc:ore/sulfur", chance: 0.2 },
      ],
      spoils: [
        { spoil: "tfc:rock/raw/quartzite", chance: 0.35 },
        { spoil: "tfc:rock/gravel/quartzite", chance: 0.15 },
      ],
    },
    coe: {
      spacing: 128,
      separation: 16,
      salt: 2995423,
      size: { min: 4, max: 6 },
      outputs: [
        Item.of("tfc_ie_addon:mineral/quartz_block").withChance(0.4),
        Item.of("tfc_ie_addon:mineral/quartz_shard").withChance(0.3),
        Item.of("tfc:ore/sulfur").withChance(0.15),
        Item.of("tfc:rock/loose/quartzite").withChance(0.15),
      ],
    },
  },
  {
    name: "stannite",
    ie: {
      weight: 25,
      failChance: 0.1,
      ores: [
        { ore: "tfc:ore/small_bismuthinite", chance: 0.16 },
        { ore: "tfc:ore/poor_bismuthinite", chance: 0.1 },
        { ore: "tfc:ore/normal_bismuthinite", chance: 0.05 },
        { ore: "tfc:ore/rich_bismuthinite", chance: 0.03 },
        { ore: "tfc_ie_addon:ore/small_galena", chance: 0.16 },
        { ore: "tfc_ie_addon:ore/poor_galena", chance: 0.1 },
        { ore: "tfc_ie_addon:ore/normal_galena", chance: 0.05 },
        { ore: "tfc_ie_addon:ore/rich_galena", chance: 0.03 },
        { ore: "tfc:ore/small_malachite", chance: 0.09 },
        { ore: "tfc:ore/poor_malachite", chance: 0.06 },
        { ore: "tfc:ore/normal_malachite", chance: 0.05 },
        { ore: "tfc:ore/rich_malachite", chance: 0.03 },
        { ore: "tfc:ore/sulfur", chance: 0.09 },
      ],
      spoils: [
        { spoil: "tfc:rock/raw/marble", chance: 0.35 },
        { spoil: "tfc:rock/gravel/marble", chance: 0.15 },
        { spoil: "tfc:rock/raw/andesite", chance: 0.35 },
        { spoil: "tfc:rock/gravel/andesite", chance: 0.15 },
      ],
    },
    coe: {
      spacing: 128,
      separation: 16,
      salt: 2252746,
      size: { min: 2, max: 4 },
      outputs: [
        Item.of("tfc:ore/normal_bismuthinite").withChance(0.25),
        Item.of("tfc:ore/rich_bismuthinite").withChance(0.1),
        Item.of("tfc_ie_addon:ore/normal_galena").withChance(0.2),
        Item.of("tfc_ie_addon:ore/rich_galena").withChance(0.1),
        Item.of("tfc:ore/normal_malachite").withChance(0.1),
        Item.of("tfc:ore/rich_malachite").withChance(0.05),
        Item.of("tfc:ore/sulfur").withChance(0.1),
        Item.of("tfc:rock/loose/marble").withChance(0.05),
        Item.of("tfc:rock/loose/andesite").withChance(0.05),
      ],
    },
  },
  {
    name: "uraninite",
    ie: {
      weight: 10,
      failChance: 0.15,
      ores: [
        { ore: "tfc_ie_addon:ore/small_uraninite", chance: 0.27 },
        { ore: "tfc_ie_addon:ore/poor_uraninite", chance: 0.19 },
        { ore: "tfc_ie_addon:ore/normal_uraninite", chance: 0.11 },
        { ore: "tfc_ie_addon:ore/rich_uraninite", chance: 0.08 },
        { ore: "tfc_ie_addon:ore/small_galena", chance: 0.13 },
        { ore: "tfc_ie_addon:ore/poor_galena", chance: 0.1 },
        { ore: "tfc_ie_addon:ore/normal_galena", chance: 0.08 },
        { ore: "tfc_ie_addon:ore/rich_galena", chance: 0.04 },
      ],
      spoils: [
        { spoil: "tfc:rock/raw/diorite", chance: 0.35 },
        { spoil: "tfc:rock/gravel/diorite", chance: 0.15 },
        { spoil: "tfc:rock/raw/chert", chance: 0.35 },
        { spoil: "tfc:rock/gravel/chert", chance: 0.15 },
      ],
    },
    coe: {
      spacing: 256,
      separation: 32,
      salt: 2129638,
      size: { min: 1, max: 2 },
      outputs: [
        Item.of("tfc_ie_addon:ore/normal_uraninite").withChance(0.35),
        Item.of("tfc_ie_addon:ore/rich_uraninite").withChance(0.2),
        Item.of("tfc_ie_addon:ore/normal_galena").withChance(0.2),
        Item.of("tfc_ie_addon:ore/rich_galena").withChance(0.1),
        Item.of("tfc:rock/loose/diorite").withChance(0.075),
        Item.of("tfc:rock/loose/chert").withChance(0.075),
      ],
    },
  },
];
