//priority: 1000

global.colorsList = [
  "white",
  "light_gray",
  "gray",
  "black",
  "brown",
  "red",
  "orange",
  "yellow",
  "lime",
  "green",
  "cyan",
  "light_blue",
  "blue",
  "purple",
  "magenta",
  "pink",
];

global.floursList = ["barley", "maize", "oat", "rye", "rice", "wheat"];

global.oreList = [
  // opal should drop from graphite and cinnabar
  {
    name: "native_copper",
    mod: "tfc",
    sand: "pink",
    gems: [],
  },
  {
    name: "native_gold",
    mod: "tfc",
    sand: "yellow",
    gems: [],
  },
  {
    name: "hematite",
    mod: "tfc",
    sand: "pink",
    gems: ["amethyst"],
    color: "#a54c4c",
  },
  {
    name: "native_silver",
    mod: "tfc",
    sand: "white",
    gems: [],
    color: "#a9adb9",
  },
  {
    name: "cassiterite",
    mod: "tfc",
    sand: "green",
    gems: ["topaz"],
    color: "#332c1e",
  },
  {
    name: "bismuthinite",
    mod: "tfc",
    sand: "green",
    gems: [],
    color: "#0a180d",
  },
  {
    name: "garnierite",
    mod: "tfc",
    sand: "green",
    gems: [],
    color: "#313c29",
  },
  {
    name: "malachite",
    mod: "tfc",
    sand: "green",
    gems: [],
    color: "#4c7a4c",
  },
  {
    name: "magnetite",
    mod: "tfc",
    sand: "black",
    gems: ["amethyst", "sapphire"],
    color: "#333337",
  },
  {
    name: "limonite",
    mod: "tfc",
    sand: "yellow",
    gems: ["amethyst"],
    color: "#937418",
  },
  {
    name: "sphalerite",
    mod: "tfc",
    sand: "white",
    gems: [],
    color: "#60626b",
  },
  {
    name: "tetrahedrite",
    mod: "tfc",
    sand: "black",
    gems: ["pyrite"],
    color: "#707070",
  },
  {
    name: "bauxite",
    mod: "tfc_ie_addon",
    sand: "pink",
    gems: [],
    color: "#a04e43",
  },
  {
    name: "galena",
    mod: "tfc_ie_addon",
    sand: "black",
    gems: ["pyrite"],
    color: "#3a343e",
  },
  {
    name: "uraninite",
    mod: "tfc_ie_addon",
    sand: "green",
    gems: [],
    color: "#6f8f58",
  },
  {
    name: "chromite",
    mod: "firmalife",
    sand: "white",
    gems: ["ruby", "sapphire"],
    color: "#9da3a5",
  },
];

global.powderList = [
  {
    name: "native_copper",
    mod: "tfc",
  },
  {
    name: "native_gold",
    mod: "tfc",
  },
  {
    name: "hematite",
    mod: "tfc",
  },
  {
    name: "native_silver",
    mod: "tfc",
  },
  {
    name: "cassiterite",
    mod: "tfc",
  },
  {
    name: "bismuthinite",
    mod: "tfc",
  },
  {
    name: "garnierite",
    mod: "tfc",
  },
  {
    name: "malachite",
    mod: "tfc",
  },
  {
    name: "magnetite",
    mod: "tfc",
  },
  {
    name: "limonite",
    mod: "tfc",
  },
  {
    name: "sphalerite",
    mod: "tfc",
  },
  {
    name: "tetrahedrite",
    mod: "tfc",
  },
  {
    name: "bauxite",
    mod: "tfc_ie_addon",
  },
  {
    name: "galena",
    mod: "tfc_ie_addon",
  },
  {
    name: "uraninite",
    mod: "tfc_ie_addon",
  },
  {
    name: "chromite",
    mod: "kubejs",
  },
];

global.smallOreYield = [
  { quality: "poor", amount: 2 },
  { quality: "normal", amount: 3 },
  { quality: "rich", amount: 4 },
];

global.sandColors = [
  "black",
  "brown",
  "green",
  "pink",
  "red",
  "white",
  "yellow",
];

global.metalToolHeads = [
  "pickaxe_head",
  "sword_blade",
  "axe_head",
  "shovel_head",
  "hoe_head",
  "chisel_head",
  "hammer_head",
  "saw_blade",
  "knife_blade",
  "scythe_blade",
  "javelin_head",
  "propick_head",
  "mace_head",
  "fish_hook",
  "prospector_hammer_head",
  "prospector_drill_head",
  "mineral_prospector_head",
];

global.toolList = [
  "pickaxe",
  "propick",
  "axe",
  "shovel",
  "hoe",
  "chisel",
  "hammer",
  "saw",
  "knife",
  "scythe",
  "javelin",
  "sword",
  "mace",
  "fishing_rod",
  "shears",
  "prospector_hammer",
  "prospector_drill",
  "mineral_prospector",
];

global.newToolMaterialList = ["osmirite"];

global.gemList = [
  "amethyst",
  "diamond",
  "emerald",
  "lapis_lazuli",
  "opal",
  "pyrite",
  "ruby",
  "sapphire",
  "topaz",
];

global.woodList = [
  "tfc:acacia",
  "tfc:ash",
  "tfc:aspen",
  "tfc:birch",
  "tfc:blackwood",
  "tfc:chestnut",
  "tfc:douglas_fir",
  "tfc:hickory",
  "tfc:kapok",
  "tfc:mangrove",
  "tfc:maple",
  "tfc:oak",
  "tfc:palm",
  "tfc:pine",
  "tfc:rosewood",
  "tfc:sequoia",
  "tfc:spruce",
  "tfc:sycamore",
  "tfc:white_cedar",
  "tfc:willow",
  "afc:baobab",
  "afc:eucalyptus",
  "afc:mahogany",
  "afc:hevea",
  "afc:tualang",
  "afc:teak",
  "afc:cypress",
  "afc:fig",
  "afc:ironwood",
  "afc:ipe",
];
//panning doesn't include deep ores and minerals for obvious (hopefully) reasons
global.panningList = [
  //SEDIMENTARY
  {
    rock: "shale",
    ores: [
      "tfc:powder/native_copper",
      //"tfc:ore/small_bismuthinite",
      //"tfc:ore/small_magnetite",
      //"tfc:ore/small_limonite",
      //"tfc_ie_addon:ore/small_bauxite",
    ],
    secondary: "tfc:rock/loose/shale",
    tertiary: "tfc:ore/borax",
  },
  {
    rock: "claystone",
    ores: [
      "tfc:powder/native_copper",
      //"tfc:ore/small_bismuthinite",
      //"tfc:ore/small_magnetite",
      //"tfc:ore/small_limonite",
      //"tfc_ie_addon:ore/small_bauxite",
    ],
    secondary: "tfc:rock/loose/claystone",
    tertiary: "tfc:ore/amethyst",
  },
  {
    rock: "limestone",
    ores: [
      "tfc:powder/native_copper",
      //"tfc:ore/small_bismuthinite",
      //"tfc:ore/small_magnetite",
      //"tfc:ore/small_limonite",
      //"tfc:ore/small_malachite",
      //"tfc_ie_addon:ore/small_bauxite",
    ],
    secondary: "tfc:rock/loose/limestone",
    tertiary: "tfc:ore/lapis_lazuli",
  },
  {
    rock: "conglomerate",
    ores: [
      "tfc:powder/native_copper",
      //"tfc:ore/small_bismuthinite",
      //"tfc:ore/small_magnetite",
      //"tfc:ore/small_limonite",
      //"tfc_ie_addon:ore/small_bauxite",
    ],
    secondary: "tfc:rock/loose/conglomerate",
    tertiary: "tfc:ore/lignite",
  },
  {
    rock: "dolomite",
    ores: [
      "tfc:powder/native_copper",
      //"tfc:ore/small_bismuthinite",
      //"tfc:ore/small_magnetite",
      //"tfc:ore/small_limonite",
      //"tfc:ore/small_malachite",
      //"tfc_ie_addon:ore/small_bauxite",
    ],
    secondary: "tfc:rock/loose/dolomite",
    tertiary: "tfc:ore/amethyst",
  },
  {
    rock: "chert",
    ores: [
      "tfc:powder/native_copper",
      //"tfc:ore/small_bismuthinite",
      //"tfc:ore/small_magnetite",
      //"tfc:ore/small_limonite",
      //"tfc_ie_addon:ore/small_bauxite",
    ],
    secondary: "tfc:rock/loose/chert",
    tertiary: "tfc:ore/ruby",
  },
  {
    rock: "chalk",
    ores: [
      "tfc:powder/native_copper",
      //"tfc:ore/small_bismuthinite",
      //"tfc:ore/small_magnetite",
      //"tfc:ore/small_limonite",
      //"tfc:ore/small_malachite",
      //"tfc_ie_addon:ore/small_bauxite",
    ],
    secondary: "tfc:rock/loose/chalk",
    tertiary: "tfc:ore/sapphire",
  },
  //METAMORPHIC
  {
    rock: "quartzite",
    ores: [
      "tfc:powder/native_copper",
      //"tfc:ore/small_tetrahedrite",
      //"firmalife:ore/small_chromite",
      //"tfc_ie_addon:ore/small_bauxite",
      //"tfc_ie_addon:ore/small_galena",
      //"tfc_ie_addon:ore/small_uraninite",
    ],
    secondary: "tfc:rock/loose/quartzite",
    tertiary: "tfc:ore/opal",
  },
  {
    rock: "slate",
    ores: [
      "tfc:powder/native_copper",
      //"tfc:ore/small_tetrahedrite",
      //"firmalife:ore/small_chromite",
      //"tfc_ie_addon:ore/small_bauxite",
      //"tfc_ie_addon:ore/small_galena",
      //"tfc_ie_addon:ore/small_uraninite",
    ],
    secondary: "tfc:rock/loose/slate",
    tertiary: "tfc:ore/pyrite",
  },
  {
    rock: "phyllite",
    ores: [
      "tfc:powder/native_copper",
      //"tfc:ore/small_tetrahedrite",
      //"firmalife:ore/small_chromite",
      //"tfc_ie_addon:ore/small_bauxite",
      //"tfc_ie_addon:ore/small_galena",
      //"tfc_ie_addon:ore/small_uraninite",
    ],
    secondary: "tfc:rock/loose/phyllite",
    tertiary: "tfc:ore/pyrite",
  },
  {
    rock: "schist",
    ores: [
      "tfc:powder/native_copper",
      //"tfc:ore/small_tetrahedrite",
      //"tfc:ore/small_native_silver",
      //"firmalife:ore/small_chromite",
      //"tfc_ie_addon:ore/small_bauxite",
      //"tfc_ie_addon:ore/small_galena",
      //"tfc_ie_addon:ore/small_uraninite",
    ],
    secondary: "tfc:rock/loose/schist",
    tertiary: "tfc:ore/pyrite",
  },
  {
    rock: "gneiss",
    ores: [
      "tfc:powder/native_copper",
      //"tfc:ore/small_tetrahedrite",
      //"tfc:ore/small_native_silver",
      //"firmalife:ore/small_chromite",
      //"tfc_ie_addon:ore/small_bauxite",
      //"tfc_ie_addon:ore/small_galena",
      //"tfc_ie_addon:ore/small_uraninite",
    ],
    secondary: "tfc:rock/loose/gneiss",
    tertiary: "tfc:ore/gypsum",
  },
  {
    rock: "marble",
    ores: [
      "tfc:powder/native_copper",
      //"tfc:ore/small_tetrahedrite",
      //"tfc:ore/small_malachite",
      //"firmalife:ore/small_chromite",
      //"tfc_ie_addon:ore/small_bauxite",
      //"tfc_ie_addon:ore/small_galena",
      //"tfc_ie_addon:ore/small_uraninite",
    ],
    secondary: "tfc:rock/loose/marble",
    tertiary: "lapis_lazuli",
  },
  //IGNEOUS EXTRUSIVE
  {
    rock: "rhyolite",
    ores: [
      "tfc:powder/native_copper",
      //"tfc:ore/small_native_copper",
      //"tfc:ore/small_native_gold",
      //"tfc:ore/small_hematite",
      //"tfc:ore/small_sphalerite",
      //"tfc_ie_addon:ore/small_galena",
      //"tfc_ie_addon:ore/small_uraninite",
    ],
    secondary: "tfc:groundcover/pumice",
    tertiary: "tfc:ore/pyrite",
  },
  {
    rock: "basalt",
    ores: [
      "tfc:powder/native_copper",
      //"tfc:ore/small_native_copper",
      //"tfc:ore/small_native_gold",
      //"tfc:ore/small_hematite",
      //"tfc:ore/small_sphalerite",
      //"tfc_ie_addon:ore/small_galena",
      //"tfc_ie_addon:ore/small_uraninite",
    ],
    secondary: "tfc:groundcover/pumice",
    tertiary: "tfc:ore/pyrite",
  },
  {
    rock: "andesite",
    ores: [
      "tfc:powder/native_copper",
      //"tfc:ore/small_native_copper",
      //"tfc:ore/small_native_gold",
      //"tfc:ore/small_hematite",
      //"tfc:ore/small_sphalerite",
      //"tfc_ie_addon:ore/small_galena",
      //"tfc_ie_addon:ore/small_uraninite",
    ],
    secondary: "tfc:rock/loose/andesite",
    tertiary: "tfc:ore/pyrite",
  },
  {
    rock: "dacite",
    ores: [
      "tfc:powder/native_copper",
      //"tfc:ore/small_native_copper",
      //"tfc:ore/small_native_gold",
      //"tfc:ore/small_hematite",
      //"tfc:ore/small_sphalerite",
      //"tfc_ie_addon:ore/small_galena",
      //"tfc_ie_addon:ore/small_uraninite",
    ],
    secondary: "tfc:groundcover/pumice",
    tertiary: "tfc:ore/pyrite",
  },
  //IGNEOUS INTRUSIVE
  {
    rock: "granite",
    ores: [
      "tfc:powder/native_copper",
      //"tfc:ore/small_native_gold",
      //"tfc:ore/small_native_silver",
      //"tfc:ore/small_cassiterite",
      //"tfc:ore/small_garnierite",
      //"firmalife:ore/small_chromite",
      //"tfc_ie_addon:ore/small_galena",
    ],
    secondary: "tfc:rock/loose/granite",
    tertiary: "tfc:ore/topaz",
  },
  {
    rock: "diorite",
    ores: [
      "tfc:powder/native_copper",
      //"tfc:ore/small_native_gold",
      //"tfc:ore/small_native_silver",
      //"tfc:ore/small_cassiterite",
      //"tfc:ore/small_garnierite",
      //"firmalife:ore/small_chromite",
      //"tfc_ie_addon:ore/small_galena",
    ],
    secondary: "tfc:rock/loose/diorite",
    tertiary: "tfc:ore/emerald",
  },
  {
    rock: "gabbro",
    ores: [
      "tfc:powder/native_copper",
      //"tfc:ore/small_native_gold",
      //"tfc:ore/small_cassiterite",
      //"firmalife:ore/small_chromite",
      //"tfc_ie_addon:ore/small_galena",
    ],
    secondary: "tfc:rock/loose/gabbro",
    tertiary: "tfc:ore/diamond",
  },
];
