//priority: 10
ServerEvents.recipes((event) => {
  const recipes = [
    //minecraft
    { id: "minecraft:charcoal" },
    //tfc & addons
    { id: /_cut$/ },
    { id: /heating\/ore/ },
    { type: "tfc:quern", output: "#may:ore_powders" },
    { type: "tfc:quern", output: "#tfc:gem_powders" },
    { id: "tfc:quern/cryolite" },
    { type: "tfc:bloomery" },
    { type: "tfc:alloy" },
    { id: /tfc:crafting\/stone\/hammer.+/ },
    { id: /tfc:rock_knapping\/hammer.+/ },
    { id: /tfc:casting\/weak.+/ },
    { id: /tfc:casting\/high_carbon_.+steel/ },
    { id: /tfc:welding\/high_carbon.+/ },
    { id: /.fc:crafting\/wood\/.+axle/ },
    { id: /.fc:crafting\/wood\/.+support/ },
    { id: /.fc:crafting\/wood\/.+clutch/ },
    { id: /.fc:crafting\/wood\/.+gear_box/ },
    { id: /.fc:crafting\/wood\/.+lumber_log/ },
    { id: "tfc:crafting/wattle" },
    { id: "tfc:shapeless/wattle" },
    { id: "firmalife:crafting/ashtray" },
    { id: "tfc:heating/kaolin_clay" },
    { id: "tfc:crafting/fire_clay" },
    { id: "tfc:crafting/fire_bricks" },
    //immersive & addons
    { type: "immersiveengineering:crusher" },
    { type: "immersiveengineering:arc_furnace" },
    { id: /immersiveengineering:crafting\/cokebrick.*/ },
    { id: "immersiveengineering:cokeoven/coke" },
    { id: "immersiveengineering:cokeoven/coke_block" },
    { id: "tfc_ie_addon:cokeoven/lignite" },
    { id: "immersiveengineering:crafting/coke_to_coal_coke" },
    { id: "immersiveengineering:crafting/coal_coke_to_coke" },
    { id: "immersiveengineering:crafting/fluorescent_tube" },
    { id: /immersiveengineering:crafting\/.*nugget.*/ },
    { id: /tfc_ie_addon:metalpress\/.+/ },
    { id: /tfc_ie_addon:cokeoven\/.+/ },
    { id: /immersivegeology:coking\/.+/ },
    //create & addons
    { id: /create:crafting\/appliances\/.*backtank.*/ },
    { id: /create:crafting\/appliances\/.*controller.*/ },
    { id: "create:crafting/kinetics/andesite_door" },
    { id: "create:crafting/kinetics/shaft" },
    { id: "create:crafting/kinetics/wrench" },
    { id: "create:crafting/kinetics/clutch" },
    { id: "create:crafting/kinetics/gearshift" },
    { id: "create:crafting/kinetics/encased_chain_drive" },
    { id: "create:crafting/kinetics/encased_chain_drive" },
    { id: "create:crafting/kinetics/adjustable_chain_gearshift" },
    { id: "create:crafting/kinetics/nozzle" },
    { id: "create:crafting/kinetics/turntable" },
    { id: "create:crafting/kinetics/hand_crank" },
    { id: "create:crafting/kinetics/millstone" },
    { id: "create:crafting/kinetics/mechanical_press" },
    { id: "create:crafting/kinetics/basin" },
    { id: "create:crafting/kinetics/empty_blaze_burner" },
    { id: "create:crafting/kinetics/depot" },
    { id: "create:crafting/kinetics/chute" },
    { id: "create:crafting/kinetics/smart_chute" },
    { type: "create:mechanical_crafting" },
    { id: /create:crafting\/schematics\/.+/ },
    { id: /create:crafting\/kinetics\/.*cogwheel.*/ },
    { id: /create:deploying\/.*cogwheel/ },
    { id: /create:.+\/andesite_alloy.*/ },
    //mekanism & addons
    { id: "mekanism:charcoal" },
    { id: "mekanism:storage_blocks/charcoal" },
    { id: /mekanism:sawing.log.+/ },
    //farmer's delight & addons
    { id: /farmersdelight:cutting\/.+wood/ },
    { id: /farmersdelight:cutting\/.+log/ },
    { id: /farmersdelight:cutting\/.+sign/ },
    { id: /farmersdelight:cutting\/.+door/ },
    { id: /farmersdelight:cutting\/.+stem/ },
    { id: /farmersdelight:cutting\/.+hyphae/ },
    { id: /farmersdelight:cutting\/.+block/ },
    { id: "farmersdelight:cooking/turtle_stew" },
    { id: /farmersrespite:.+\/water_cup/ },
    // AE2 & addons
    { id: /ae2:tools\/.+/ },
  ];

  recipes.forEach((recipe) => {
    event.remove(recipe);
  });
});
