//priority: 10
ServerEvents.recipes((event) => {
  const recipes = [
    //minecraft
    { type: "minecraft:blasting" },
    { type: "minecraft:smoking" },
    { type: "minecraft:smelting" },
    { id: "minecraft:charcoal" },
    { id: "minecraft:cauldron" },
    { id: "minecraft:leather" },
    { output: "minecraft:netherrack" },
    { id: "minecraft:sea_lantern" },
    { id: "minecraft:iron_ingot_from_nuggets" },
    { output: "minecraft:iron_bars" },
    { output: "minecraft:chain" },
    { id: "minecraft:heavy_weighted_pressure_plate" },
    { id: /minecraft:netherite.+smithing/ },
    { id: /minecraft:.+_nugget_from_.+/ },
    {
      output:
        /minecraft:.*((oak)|(spruce)|(birch)|(jungle)|(acacia)|(mangrove)|(cherry)|(bamboo)|(crimson)|(warped)).+/,
    },
    {
      output:
        /minecraft:.*((deepslate)|(sandstone)|(andesite)|(granite)|(diorite)|(nether_brick)|(smooth_stone)|(blackstone)|(end_stone)|(purpur)|(prismarin)|(stone_brick)|(mossy)|(cobblestone)|(basalt)).*/,
    },
    { output: /minecraft:.*copper(?!_ingot).*/ },
    { output: /minecraft:stone(?!cutter).*/ },
    { output: /minecraft:.*ore/ },
    {
      output:
        /minecraft:((coal)|(iron)|(gold)|(emerald)|(lapis)|(diamond)|(netherite))_block/,
    },
    { input: /minecraft:((iron)|(golden)|(diamond))_horse_armor/ },

    //tfc & addons
    { id: /_cut$/ },
    { id: /heating\/ore/ },
    { type: "tfc:quern", output: "#may:ore_powders" },
    { type: "tfc:quern", output: "#tfc:gem_powders" },
    { id: "tfc:quern/cryolite" },
    { id: "tfc:quern/blaze_rod" },
    { type: "tfc:bloomery" },
    { type: "tfc:alloy" },
    { id: /tfc:crafting\/stone\/hammer.+/ },
    { id: /tfc:rock_knapping\/hammer.+/ },
    { id: /tfc:casting\/weak.+/ },
    { id: /tfc:casting\/high_carbon_.+steel/ },
    { id: /tfc:welding\/high_carbon.+/ },
    { id: /.fc:crafting\/wood\/.+axle/ },
    { id: /.fc:crafting\/wood\/.+support/ },
    { id: /.fc:crafting\/wood\/.+clutch/ },
    { id: /.fc:crafting\/wood\/.+gear_box/ },
    { id: /.fc:crafting\/wood\/.+lumber_log/ },
    { id: "tfc:crafting/wattle" },
    { id: "tfc:shapeless/wattle" },
    { id: "firmalife:crafting/ashtray" },
    { id: "tfc:heating/kaolin_clay" },
    { id: "tfc:crafting/fire_clay" },
    { id: "tfc:crafting/fire_bricks" },
    { id: "tfc:crafting/wool_yarn" },
    { id: "tfc:crafting/bloomery" },
    { id: "firmalife:crafting/pineapple_yarn" },
    { id: /tfc:barrel\/((large)|(medium)|(small))_((soaked)|(prepared))_hide/ },
    { id: /tfc:barrel\/((large)|(medium)|(small))_leather/ },
    { id: /firmaciv:barrel\/large_waterproof_hide_.+/ },
    { id: "firmaciv:crafting/large_waterproof_hide" },
    { id: "tfc_ie_addon:heating/metal/lead_ingot" },
    { id: "tfc_ie_addon:heating/metal/uranium_ingot" },

    //immersive & addons
    { type: "immersiveengineering:crusher" },
    { type: "immersiveengineering:arc_furnace" },
    { id: /immersiveengineering:crafting\/cokebrick.*/ },
    { id: "immersiveengineering:cokeoven/coke" },
    { id: "immersiveengineering:cokeoven/coke_block" },
    { id: "tfc_ie_addon:cokeoven/lignite" },
    { id: "immersiveengineering:crafting/coke_to_coal_coke" },
    { id: "immersiveengineering:crafting/coal_coke_to_coke" },
    { id: "immersiveengineering:crafting/fluorescent_tube" },
    { id: "immersiveengineering:crafting/tinted_glass_lead_wire" },
    { id: /immersiveengineering:crafting\/.*hammer.*/ },
    { id: /immersiveengineering:crafting\/.*nugget.*/ },
    { id: /tfc_ie_addon:metalpress\/.+/ },
    { id: /tfc_ie_addon:cokeoven\/.+/ },
    { id: /immersivegeology:coking\/.+/ },
    { id: "immersivegeology:crafting/get_nuggets_from_steel_ingot" },
    { id: "immersivegeology:crafting/craft_igtoolkit_0" },
    { id: "immersivegeology:crafting/craft_steel_geologist_pick" },
    { id: "immersiveengineering:blastfurnace/steel" },
    { id: "immersiveengineering:blastfurnace/steel_block" },
    { type: "immersiveengineering:alloy" },
    { id: "immersiveengineering:squeezer/graphite_dust" },
    { id: "immersivepetroleum:squeezer/graphite_dust" },
    { id: "immersiveengineering:blueprint/graphite_electrode" },
    { id: "immersiveengineering:metalpress/electrode" },
    { id: "tfc_ie_addon:heating/hop_graphite_ingot" },
    { type: "advancedtfctech:beamhouse" },

    //create & addons
    { id: "create:crafting/appliances/copper_backtank" },
    { id: /create:crafting\/appliances\/.*controller.*/ },
    { id: "create:crafting/kinetics/andesite_door" },
    { id: "create:crafting/kinetics/shaft" },
    { id: "create:crafting/kinetics/wrench" },
    { id: "create:crafting/kinetics/clutch" },
    { id: "create:crafting/kinetics/gearshift" },
    { id: "create:crafting/kinetics/encased_chain_drive" },
    { id: "create:crafting/kinetics/encased_chain_drive_from_zinc" },
    { id: "create:crafting/kinetics/adjustable_chain_gearshift" },
    { id: "create:crafting/kinetics/nozzle" },
    { id: "create:crafting/kinetics/turntable" },
    { id: "create:crafting/kinetics/hand_crank" },
    { id: "create:crafting/kinetics/millstone" },
    { id: "create:crafting/kinetics/mechanical_press" },
    { id: "create:crafting/kinetics/basin" },
    { id: "create:crafting/kinetics/empty_blaze_burner" },
    { id: "create:crafting/kinetics/depot" },
    { id: "create:crafting/kinetics/chute" },
    { id: "create:crafting/kinetics/smart_chute" },
    { id: "create:crafting/kinetics/belt_connector" },
    { id: "create:crafting/kinetics/chain_conveyor" },
    { id: "create:crafting/kinetics/water_wheel" },
    { id: "create:crafting/kinetics/large_water_wheel" },
    { id: "create:crafting/kinetics/metal_bracket" },
    { id: "create:crafting/kinetics/fluid_pipe" },
    { id: "create:crafting/kinetics/fluid_pipe_vertical" },
    { id: "create:crafting/kinetics/smart_fluid_pipe" },
    { id: "create:crafting/kinetics/fluid_valve" },
    { id: "create:crafting/kinetics/copper_valve_handle" },
    { id: "create:crafting/kinetics/fluid_tank" },
    { id: "create:crafting/kinetics/hose_pulley" },
    { id: "create:crafting/kinetics/item_drain" },
    { id: "create:crafting/kinetics/steam_engine" },
    { id: "create:crafting/kinetics/steam_whistle" },
    { id: "create:crafting/kinetics/elevator_pulley" },
    { type: "create:mechanical_crafting" },
    { type: "create:haunting" },
    { type: "create:splashing" },
    { type: "create:milling" },
    { id: /create:crafting\/schematics\/.+/ },
    { id: /create:crafting\/kinetics\/.*cogwheel.*/ },
    { id: /create:deploying\/.*cogwheel/ },
    { id: /create:.+\/andesite_alloy.*/ },
    { id: /railways:.*locometal.*/ },
    { id: /railways:sequenced_assembly\/track.+/ },
    { id: "create:sequenced_assembly/track" },
    { id: "create:sequenced_assembly/precision_mechanism" },
    { id: "create:pressing/copper_ingot" },
    { id: "create:crushing/leather_horse_armor" },
    { id: "create:crushing/saddle" },
    { output: /create:crushed.*/ },
    { input: "createoreexcavation:raw_diamond" },
    { input: "createoreexcavation:raw_emerald" },
    { input: "createoreexcavation:raw_redstone" },
    { id: "createoreexcavation:drill" },
    { id: "createoreexcavation:diamond_drill" },
    { id: "createaddition:crafting/electrum_nugget" },
    { id: "createaddition:rolling/copper_ingot" },
    { id: "createaddition:compat/immersiveengineering/crushing/steel_ingot" },
    { id: "createaddition:crushing/moon_cheese_ore" },

    //mekanism & addons
    { id: "mekanism:charcoal" },
    { id: "mekanism:storage_blocks/charcoal" },
    { id: /mekanism:sawing.+/ },
    { id: /mekanism:nucleosynthesizing\/.+/ },
    //{ id: "mekanism:storage_blocks/steel" }, NOT WORKING

    //farmer's delight & addons
    { id: /farmersdelight:cutting\/.+wood/ },
    { id: /farmersdelight:cutting\/.+log/ },
    { id: /farmersdelight:cutting\/.+sign/ },
    { id: /farmersdelight:cutting\/.+door/ },
    { id: /farmersdelight:cutting\/.+stem/ },
    { id: /farmersdelight:cutting\/.+hyphae/ },
    { id: /farmersdelight:cutting\/.+block/ },
    { id: /farmersdelight:cutting\/leather.+/ },
    { id: /farmersdelight:cutting\/.*bricks/ },
    { id: "farmersdelight:cutting/gravel" },
    { id: "farmersdelight:cutting/clay" },
    { id: "farmersdelight:cutting/stone" },
    { id: "farmersdelight:cutting/deepslate" },
    { id: "farmersdelight:cooking/turtle_stew" },
    { id: /farmersrespite:.+\/water_cup/ },

    // AE2 & addons
    { id: /ae2:.*((axe)|(knife)|(shovel)|(hoe)|(sword)).*/ },
    { id: /ae2:transform\/.+/ },

    //Pneumatic Craft
    { id: "pneumaticcraft:amadron_tablet" },
    { id: /pneumaticcraft:pressure_chamber\/pressure_chamber_.*enchanting/ },

    //ad astra
    //{ id: "ad_astra:steel_nugget" }, NOT WORKING
    { id: "ad_astra:alloying/steel_ingot_from_alloying_iron_ingot_and_coals" },
    { id: "ad_astra:compressing/iron_plate_from_compressing_iron_ingot" },
    { id: "ad_astra:astrodux" },

    // Misc
    { id: "ftbquests:loot_crate_opener" },
    { id: "cold_sweat:thermometer" },
  ];

  recipes.forEach((recipe) => {
    event.remove(recipe);
  });
});
