#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu Aug 21 21:16:51 MSK 2025
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=
enableShaders=true
