ServerEvents.tags("item", (event) => {
  event.removeAllTagsFrom(/^minecraft:.+((log)|(wood)|(stem)|(hyphae))$/);
  event.removeAllTagsFrom(
    /^minecraft:((wooden)|(stone)|(chainmail)|(iron)|(golden)|(diamond)|(netherite))_((shovel)|(pickaxe)|(axe)|(hoe)|(sword)|(helmet)|(chestplate)|(leggings)|(boots))$/
  );
  event.removeAllTagsFrom(/^ad_astra:.+((log)|(wood)|(stem)|(hyphae))$/);
  event.removeAllTagsFrom("create:brass_ingot");
  event.removeAllTagsFrom("createaddition:electrum_ingot");
  event.removeAllTagsFrom("immersiveengineering:ingot_steel");
  event.removeAllTagsFrom("ad_astra:steel_ingot");
  event.removeAllTagsFrom("mekanism:ingot_steel");
  event.removeAllTagsFrom("minecraft:gold_ingot");
  event.removeAllTagsFrom("minecraft:copper_ingot");
  event.removeAllTagsFrom("create:zinc_ingot");
  event.removeAllTagsFrom("immersivegeology:ingot_zinc");
  event.removeAllTagsFrom("immersivegeology:ingot_bronze");
  event.removeAllTagsFrom("immersivegeology:ingot_tin");
  event.removeAllTagsFrom("immersiveengineering:ingot_silver");
  event.removeAllTagsFrom("immersiveengineering:ingot_nickel");
  event.removeAllTagsFrom("immersivegeology:ingot_chromium");
  event.removeAllTagsFrom("immersivegeology:ingot_osmium");
  event.removeAllTagsFrom("immersivegeology:ingot_stainless_steel");
  event.removeAllTagsFrom("immersivegeology:ingot_lignite");
  event.removeAllTagsFrom("mekanism:ingot_bronze");
  event.removeAllTagsFrom("mekanism:ingot_tin");
  event.removeAllTagsFrom("immersiveengineering:ingot_lead");
  event.removeAllTagsFrom("immersiveengineering:ingot_uranium");
  event.removeAllTagsFrom("minecraft:iron_ingot");
  event.removeAllTagsFrom("immersiveengineering:stick_iron");
  event.removeAllTagsFrom("immersiveengineering:stick_steel");
  event.removeAllTagsFrom("immersiveengineering:stick_aluminum");
});
